services:
  - type: web
    name: flask-crud-supabase
    runtime: python
    region: oregon
    plan: free

    buildCommand: pip install -r requirements.txt

    startCommand: gunicorn app:app

    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7

      - key: FLASK_ENV
        value: production

      - key: FLASK_APP
        value: app.py

      - key: SUPABASE_DB_URL
        sync: false

      - key: SECRET_KEY
        generateValue: true

      - key: LOG_LEVEL
        value: INFO